["poetrel:major"]
color = "ff0000"
name = "poetrel:major"
description = "Release a new major version"

["poetrel:minor"]
color = "ff7f00"
name = "poetrel:minor"
description = "Release a new minor version"

["poetrel:no-bump"]
color = "0000ff"
name = "poetrel:no-bump"
description = "Release without bumping the pyproject.toml version"

["poetrel:patch"]
color = "ffff00"
name = "poetrel:patch"
description = "Release a new patch version"

["poetrel:premajor"]
color = "7f0000"
name = "poetrel:premajor"
description = "Release a pre-major version"

["poetrel:preminor"]
color = "7f3f00"
name = "poetrel:preminor"
description = "Release a pre-minor version"

["poetrel:prepatch"]
color = "7f7f00"
name = "poetrel:prepatch"
description = "Release a pre-patch version"

["poetrel:prerelease"]
color = "00ff00"
name = "poetrel:prerelease"
description = "Release a pre-release version"

["poetrel:prerelease --next-phase"]
color = "007f00"
name = "poetrel:prerelease --next-phase"
description = "Release a pre-release version with incremented phase"
