name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Release
        uses: corentin-regent/poetrel/release-gh-action@auto-release
        with:
          changelog: CHANGELOG.md
