name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Release project
        uses: corentin-regent/poetrel@b13bac35c1f31a676defa521408fed58644a1d60
        with:
          changelog: CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
