name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Release project
        uses: corentin-regent/poetrel@v1
        with:
          changelog: CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}

  post-release:
    name: Post Release
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Check out develop
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.PAT }}

      - name: Synchronize develop branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge origin/main
          git push
